// <auto-generated />
using System;
using Cuida_.Models.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuida_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103174545_Create_MedicoCampanha")]
    partial class Create_MedicoCampanha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cuida_.Models.CampanhasAderidas.AderirCampanhas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdericao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AderirCampanhas");
                });

            modelBuilder.Entity("Cuida_.Models.campanhas.Campanha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCampanha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("Cuida_.Models.campanhas.MedicoCampanha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("MedicoId", "CampanhaId")
                        .IsUnique();

                    b.ToTable("MedicoCampanha", (string)null);
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Clinica", b =>
                {
                    b.HasBaseType("Cuida_.Models.usuarios.Usuario");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Medico", b =>
                {
                    b.HasBaseType("Cuida_.Models.usuarios.Usuario");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HorariosDisponiveis")
                        .HasColumnType("longtext");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Paciente", b =>
                {
                    b.HasBaseType("Cuida_.Models.usuarios.Usuario");

                    b.Property<int>("CadUnico")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Cuida_.Models.campanhas.Campanha", b =>
                {
                    b.HasOne("Cuida_.Models.usuarios.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Cuida_.Models.campanhas.MedicoCampanha", b =>
                {
                    b.HasOne("Cuida_.Models.campanhas.Campanha", "Campanha")
                        .WithMany("MedicoCampanhas")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuida_.Models.usuarios.Medico", "Medico")
                        .WithMany("MedicoCampanhas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Clinica", b =>
                {
                    b.HasOne("Cuida_.Models.usuarios.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Cuida_.Models.usuarios.Clinica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Medico", b =>
                {
                    b.HasOne("Cuida_.Models.usuarios.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Cuida_.Models.usuarios.Medico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Paciente", b =>
                {
                    b.HasOne("Cuida_.Models.usuarios.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Cuida_.Models.usuarios.Paciente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cuida_.Models.campanhas.Campanha", b =>
                {
                    b.Navigation("MedicoCampanhas");
                });

            modelBuilder.Entity("Cuida_.Models.usuarios.Medico", b =>
                {
                    b.Navigation("MedicoCampanhas");
                });
#pragma warning restore 612, 618
        }
    }
}
